FROM bmsc-base:latest

RUN Rscript -e "install.packages('BMSC')"

RUN Rscript -e "install.packages(c('shinythemes', 'futile.logger', 'DT','shinyjs','openxlsx','car','jsonlite','shinyWidgets','pROC','Rcpp'))"